repos:
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: yarn prettier --write .
        language: system

      - id: eslint
        name: eslint
        entry: yarn eslint --fix
        language: system

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.21.2
    hooks:
      - id: gitleaks
